language: objective-c
os: osx
osx_image:
  - xcode11.3
  - xcode11.2
  - xcode10.3
  - xcode10.2 # For iOS 9 support.
env:
  - TOOLCHAIN=bazel
  - PROJECT="Examples/MDFTestingExample"
jobs:
  include:
    - name: "pod lib lint"
      osx_image: xcode11.3
      env: TOOLCHAIN=cocoapods
before_install:
  - if [ "$TOOLCHAIN" == "bazel" ]; then
      wget -O bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.2.1/bazelisk-darwin-amd64";
      if [ "$(cat bazelisk | openssl sha256 -sha256)" != "edeeebb65f4757c802cd7a479fb86622c3de46a0fa313e6bcbc2efdd37a588b3" ]; then
        echo "Bazelisk SHA mismatch.";
        exit 1;
      fi;
      chmod +x "bazelisk";
    fi
script:
  - if [ "$TOOLCHAIN" == "bazel" ]; then
      ./bazelisk test //...;
    elif [ "$TOOLCHAIN" == "cocoapods" ]; then
      pod lib lint;
    elif [ "$PROJECT" == "Examples/MDFTestingExample" ]; then
      set -o pipefail;
      pod install --project-directory=Examples;
      xcodebuild build
        -workspace "$PROJECT.xcworkspace"
        -scheme MDFTestingExample
        -destination "platform=iOS Simulator,name=iPhone Xs Max,OS=12.2" | xcpretty;
    fi
